export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILED = 'FETCH_NEWS_FAILED';

export const ADD_NEWS_SUCCESS = 'ADD_NEWS_SUCCESS';
export const ADD_NEWS_FAILED = 'ADD_NEWS_FAILED';

export const DELETE_NEWS_SUCCESS = 'DELETE_NEWS_SUCCESS';
export const DELETE_NEWS_FAILED = 'DELETE_NEWS_FAILED';

export const UPDATE_NEWS_SUCCESS = 'UPDATE_NEWS_SUCCESS';
export const UPDATE_NEWS_FAILED = 'UPDATE_NEWS_FAILED';

export const FETCH_LIKE_SUCCESS = 'FETCH_LIKE_SUCCESS';
export const FETCH_LIKE_FAILED = 'FETCH_LIKE_FAILED';

export const LIKE_NEWS_SUCCESS = 'LIKE_NEWS_SUCCESS';
export const LIKE_NEWS_FAILED = 'LIKE_NEWS_FAILED';


export const UNLIKE_NEWS_SUCCESS = 'UNLIKE_NEWS_SUCCESS';
export const UNLIKE_NEWS_FAILED = 'UNLIKE_NEWS_FAILED';

