export const SHOW_LOADING_LOGIN = "SHOW_LOADING_LOGIN";
export const HIDE_LOADING_LOGIN = "HIDE_LOADING_LOGIN";
export const SHOW_LOADING_SIGNUP = "SHOW_LOADING_SIGNUP";
export const HIDE_LOADING_SIGNUP = "HIDE_LOADING_SIGNUP";