export const FETCH_CURRENT_USER = "FETCH_CURRENT_USER";

export const ADD_AVATAR_USER_SUCCESS = "ADD_AVATAR_USER_SUCCESS";
export const ADD_AVATAR_USER_FAILED = "ADD_AVATAR_USER_FAILED";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
